name: LeetcodeSync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
    
jobs:
  leetcode-sync:
    runs-on: ubuntu-latest
    steps:
    
      - name: Sync me Leetcode
        uses: oneshan/leetcode-sync-in-action@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LEETCODE_CSRF_TOKEN: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
